var hierarchy =
[
    [ "ADDAC", "class_a_d_d_a_c.html", null ],
    [ "ADDAC_AD", "class_a_d_d_a_c___a_d.html", null ],
    [ "ADDAC_Adsr", "class_a_d_d_a_c___adsr.html", null ],
    [ "ADDAC_Boid", "class_a_d_d_a_c___boid.html", null ],
    [ "ADDAC_Clock", "class_a_d_d_a_c___clock.html", null ],
    [ "ADDAC_Comparator", "class_a_d_d_a_c___comparator.html", null ],
    [ "ADDAC_CVbuffer", "class_a_d_d_a_c___c_vbuffer.html", null ],
    [ "ADDAC_CVlooper", "class_a_d_d_a_c___c_vlooper.html", null ],
    [ "ADDAC_DMX", "class_a_d_d_a_c___d_m_x.html", null ],
    [ "ADDAC_dmxChannel", "class_a_d_d_a_c__dmx_channel.html", null ],
    [ "ADDAC_Empty", "class_a_d_d_a_c___empty.html", null ],
    [ "ADDAC_Env", "class_a_d_d_a_c___env.html", null ],
    [ "ADDAC_Euclidean", "class_a_d_d_a_c___euclidean.html", null ],
    [ "ADDAC_Flock", "class_a_d_d_a_c___flock.html", null ],
    [ "ADDAC_GateDelay", "class_a_d_d_a_c___gate_delay.html", null ],
    [ "ADDAC_LFO", "class_a_d_d_a_c___l_f_o.html", null ],
    [ "ADDAC_Lin2Log", "class_a_d_d_a_c___lin2_log.html", null ],
    [ "ADDAC_Liss", "class_a_d_d_a_c___liss.html", null ],
    [ "ADDAC_Logic", "class_a_d_d_a_c___logic.html", null ],
    [ "ADDAC_Midi", "class_a_d_d_a_c___midi.html", [
      [ "ADDAC_CvToMidi", "class_a_d_d_a_c___cv_to_midi.html", null ]
    ] ],
    [ "ADDAC_Ntof", "class_a_d_d_a_c___ntof.html", null ],
    [ "ADDAC_Physics", "class_a_d_d_a_c___physics.html", null ],
    [ "ADDAC_Probabilistic", "class_a_d_d_a_c___probabilistic.html", null ],
    [ "ADDAC_PVector", "class_a_d_d_a_c___p_vector.html", null ],
    [ "ADDAC_Quad", "class_a_d_d_a_c___quad.html", null ],
    [ "ADDAC_Quantizer", "class_a_d_d_a_c___quantizer.html", null ],
    [ "ADDAC_Random", "class_a_d_d_a_c___random.html", null ],
    [ "ADDAC_Smooth", "class_a_d_d_a_c___smooth.html", null ],
    [ "ADDAC_SuperFormula", "class_a_d_d_a_c___super_formula.html", null ],
    [ "ADDAC_Timer", "class_a_d_d_a_c___timer.html", null ],
    [ "ADDAC_VCO", "class_a_d_d_a_c___v_c_o.html", null ],
    [ "ADDAgateSequencer", "class_a_d_d_agate_sequencer.html", null ],
    [ "channel_n", "structchannel__n.html", null ],
    [ "midimsg", "structmidimsg.html", null ]
];